server:
  port: ${HTTP_SERVER_PORT:8012}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/outbox_service_second
    username: postgres
    password: admin

swagger:
  version: 1.0
  title: "MAIN SERVICE | DOCS"
  description: "API FOR MAIN SERVICE"