spring:
  profiles:
    active: dev
  kafka:
    bootstrap-servers: 10.11.12.13:9092
    producer:
      bootstrap-servers: 10.11.12.13:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    topic:
      name: dev-topic
  main:
    banner-mode: off
  output:
    ansi:
      enabled: always
  task:
    scheduling:
      pool:
        size: 1
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.schema.internal.HibernateSchemaManagementTool$1.doProcessImportFiles

    hibernate:
      ddl-auto: validate



logging:
  file:
    path: src/main/resources/log